/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ProjectController;
import controller.TaskController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import model.Project;
import model.Task;
import util.ButtonColorCellRenderer;
import util.DeadlineColumnCellRenderer;
import util.TaskTableModel;

/**
 *
 * @author Wellington F.
 */
public class MainScreen extends javax.swing.JFrame {

    ProjectController projectController;
    TaskController taskController;
    DefaultListModel projectsModel;
    TaskTableModel taskModel;

    public MainScreen() {
        initComponents();
        initDataController();
        initComponentsModel();
        decoraTableTask();
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneTasks = new javax.swing.JScrollPane();
        tabTasks = new javax.swing.JTable();
        PanToolBar = new javax.swing.JPanel();
        lblToolBarTitle = new javax.swing.JLabel();
        lblToolBarSubTitle = new javax.swing.JLabel();
        PanProjects = new javax.swing.JPanel();
        lblProjectsTitle = new javax.swing.JLabel();
        lblProjectsAdd = new javax.swing.JLabel();
        PanTasks = new javax.swing.JPanel();
        lblTasksTitle = new javax.swing.JLabel();
        lblTasksAdd = new javax.swing.JLabel();
        PanProjectsList = new javax.swing.JPanel();
        ScrollProjects = new javax.swing.JScrollPane();
        listProjects = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        PanEmptyList = new javax.swing.JPanel();
        lblEmptyIcon = new javax.swing.JLabel();
        lblEmptyTitle = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        tabTasks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabTasks.setGridColor(new java.awt.Color(255, 255, 255));
        tabTasks.setRowHeight(50);
        tabTasks.setSelectionBackground(new java.awt.Color(153, 255, 153));
        tabTasks.setShowVerticalLines(false);
        tabTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabTasksMouseClicked(evt);
            }
        });
        jScrollPaneTasks.setViewportView(tabTasks);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        PanToolBar.setBackground(new java.awt.Color(0, 153, 102));

        lblToolBarTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblToolBarTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblToolBarTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N
        lblToolBarTitle.setText("Todo App");

        lblToolBarSubTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblToolBarSubTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblToolBarSubTitle.setText("Anote tudo, não esqueça de nada");

        javax.swing.GroupLayout PanToolBarLayout = new javax.swing.GroupLayout(PanToolBar);
        PanToolBar.setLayout(PanToolBarLayout);
        PanToolBarLayout.setHorizontalGroup(
            PanToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanToolBarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblToolBarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblToolBarSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanToolBarLayout.setVerticalGroup(
            PanToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanToolBarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblToolBarTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblToolBarSubTitle)
                .addContainerGap())
        );

        PanProjects.setBackground(new java.awt.Color(255, 255, 255));
        PanProjects.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblProjectsTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblProjectsTitle.setForeground(new java.awt.Color(0, 153, 102));
        lblProjectsTitle.setText("Projetos");

        lblProjectsAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        lblProjectsAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProjectsAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanProjectsLayout = new javax.swing.GroupLayout(PanProjects);
        PanProjects.setLayout(PanProjectsLayout);
        PanProjectsLayout.setHorizontalGroup(
            PanProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProjectsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblProjectsAdd)
                .addContainerGap())
        );
        PanProjectsLayout.setVerticalGroup(
            PanProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProjectsAdd)
                    .addComponent(lblProjectsTitle))
                .addContainerGap())
        );

        PanTasks.setBackground(new java.awt.Color(255, 255, 255));
        PanTasks.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTasksTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTasksTitle.setForeground(new java.awt.Color(0, 153, 102));
        lblTasksTitle.setText("Tarefas");

        lblTasksAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        lblTasksAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTasksAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanTasksLayout = new javax.swing.GroupLayout(PanTasks);
        PanTasks.setLayout(PanTasksLayout);
        PanTasksLayout.setHorizontalGroup(
            PanTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTasksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTasksAdd)
                .addGap(19, 19, 19))
        );
        PanTasksLayout.setVerticalGroup(
            PanTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTasksAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTasksTitle))
                .addContainerGap())
        );

        PanProjectsList.setBackground(new java.awt.Color(255, 255, 255));
        PanProjectsList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        listProjects.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        listProjects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listProjects.setFixedCellHeight(50);
        listProjects.setSelectionBackground(new java.awt.Color(0, 153, 102));
        listProjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listProjectsMouseClicked(evt);
            }
        });
        ScrollProjects.setViewportView(listProjects);

        javax.swing.GroupLayout PanProjectsListLayout = new javax.swing.GroupLayout(PanProjectsList);
        PanProjectsList.setLayout(PanProjectsListLayout);
        PanProjectsListLayout.setHorizontalGroup(
            PanProjectsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanProjectsListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollProjects)
                .addContainerGap())
        );
        PanProjectsListLayout.setVerticalGroup(
            PanProjectsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanProjectsListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollProjects)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.BorderLayout());

        PanEmptyList.setBackground(new java.awt.Color(255, 255, 255));

        lblEmptyIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmptyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

        lblEmptyTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmptyTitle.setForeground(new java.awt.Color(0, 153, 102));
        lblEmptyTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmptyTitle.setText("Nenhuma tarefa por aqui");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Clique no botão + para adicionar uma nova tarefa");

        javax.swing.GroupLayout PanEmptyListLayout = new javax.swing.GroupLayout(PanEmptyList);
        PanEmptyList.setLayout(PanEmptyListLayout);
        PanEmptyListLayout.setHorizontalGroup(
            PanEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanEmptyListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmptyTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmptyIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)))
        );
        PanEmptyListLayout.setVerticalGroup(
            PanEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanEmptyListLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblEmptyIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmptyTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(PanEmptyList, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanProjectsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanProjectsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblProjectsAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProjectsAddMouseClicked
        ProjectDialogScreen projectDialogScreen = new ProjectDialogScreen(this, true);
        projectDialogScreen.setVisible(true);
        projectDialogScreen.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                MainScreen.this.loadProjects();
            }
        });
    }//GEN-LAST:event_lblProjectsAddMouseClicked

    private void lblTasksAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTasksAddMouseClicked
        TasksDialogScreen taskDialogScreen = new TasksDialogScreen(this, rootPaneCheckingEnabled);
        int projectIndex = listProjects.getSelectedIndex();
        Project project = (Project)projectsModel.get(projectIndex);
        taskDialogScreen.setProject(project);
        taskDialogScreen.setVisible(true);
        taskDialogScreen.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosed(WindowEvent e){
            int projectIndex = listProjects.getSelectedIndex();
            Project project = (Project)projectsModel.get(projectIndex);
            loadTasks(project.getId());
            }
        
            });
    }//GEN-LAST:event_lblTasksAddMouseClicked

    private void tabTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabTasksMouseClicked
        int rowIndex = tabTasks.rowAtPoint(evt.getPoint());
        int columnIndex = tabTasks.columnAtPoint(evt.getPoint());
        Task task = taskModel.getTasks().get(rowIndex);
        switch (columnIndex) {
            case 3:
                
                taskController.update(task);
                break;
            case 4:
                break;
            case 5:
                taskController.removeById(task.getId());
                taskModel.getTasks().remove(task);
                int projectIndex = listProjects.getSelectedIndex();
                Project project = (Project)projectsModel.get(projectIndex);
                loadTasks(project.getId());
                break;
        }
    }//GEN-LAST:event_tabTasksMouseClicked

    private void listProjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listProjectsMouseClicked
        int projectIndex = listProjects.getSelectedIndex();
        Project project = (Project)projectsModel.get(projectIndex);
        loadTasks(project.getId());
    }//GEN-LAST:event_listProjectsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanEmptyList;
    private javax.swing.JPanel PanProjects;
    private javax.swing.JPanel PanProjectsList;
    private javax.swing.JPanel PanTasks;
    private javax.swing.JPanel PanToolBar;
    private javax.swing.JScrollPane ScrollProjects;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPaneTasks;
    private javax.swing.JLabel lblEmptyIcon;
    private javax.swing.JLabel lblEmptyTitle;
    private javax.swing.JLabel lblProjectsAdd;
    private javax.swing.JLabel lblProjectsTitle;
    private javax.swing.JLabel lblTasksAdd;
    private javax.swing.JLabel lblTasksTitle;
    private javax.swing.JLabel lblToolBarSubTitle;
    private javax.swing.JLabel lblToolBarTitle;
    private javax.swing.JList<String> listProjects;
    private javax.swing.JTable tabTasks;
    // End of variables declaration//GEN-END:variables

    public void decoraTableTask() {
        //Customizando o herder da table de tarefas
        tabTasks.getTableHeader().setFont(new Font("Segoi UI", Font.BOLD, 14));
        tabTasks.getTableHeader().setBackground(new Color(0, 153, 102));
        tabTasks.getTableHeader().setForeground(new Color(255, 255, 255));
        
        tabTasks.getColumnModel().getColumn(2).setCellRenderer(new DeadlineColumnCellRenderer());
        tabTasks.getColumnModel().getColumn(4).setCellRenderer(new ButtonColorCellRenderer("edit"));
        tabTasks.getColumnModel().getColumn(5).setCellRenderer(new ButtonColorCellRenderer("delete"));

        //Criando um sort automático para a coluna da table
        //tabTasks.setAutoCreateRowSorter(true);
    }

    public void initDataController() {
        projectController = new ProjectController();
        taskController = new TaskController();
    }

    public void initComponentsModel() {
        projectsModel = new DefaultListModel();
        loadProjects();

        taskModel = new TaskTableModel();
        tabTasks.setModel(taskModel);
        
        if(!projectsModel.isEmpty()){
            listProjects.setSelectedIndex(0);
            Project project = (Project) projectsModel.get(0);
            loadTasks (project.getId());
        }
    }

    public void loadTasks(int idProject) {
        List<Task> tasks = taskController.getByProjectId(idProject);
        taskModel.setTasks(tasks);
        showJTableTasks(!tasks.isEmpty());

    }
    
    private void showJTableTasks(boolean hasTasks) {
        if (hasTasks) {
            //Existem tarefas
            if (PanEmptyList.isVisible()) {
                PanEmptyList.setVisible(false);
                jPanel5.remove(PanEmptyList);
            }

            jPanel5.add(jScrollPaneTasks);
            jScrollPaneTasks.setVisible(true);
            jScrollPaneTasks.setSize(jPanel5.getWidth(),jPanel5.getHeight());
        } else {
            if (jScrollPaneTasks.isVisible()) {
                jScrollPaneTasks.setVisible(false);
                jPanel5.remove(jScrollPaneTasks);
            }

            jPanel5.add(this.PanEmptyList);
            PanEmptyList.setVisible(true);
            PanEmptyList.setSize(jPanel5.getWidth(),jPanel5.getHeight());
        }

    }

    public void loadProjects() {
        List<Project> projects = projectController.getAll();
        projectsModel.clear();
        for (int i = 0; i < projects.size(); i++) {
            Project project = projects.get(i);
            projectsModel.addElement(project);
        }
        listProjects.setModel(projectsModel);
    }
}
